/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ProjetoVendas;

import ProjetoVendas.View.frmCliente;

public class App {       
    

    public static void main(String[] args) {
        
        frmCliente form = new frmCliente();
        form.setVisible(true);
    }
}
