/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ProjetoVendas;

import ProjetoVendas.View.frmCliente;
import ProjetoVendas.View.frmLogin;

public class App {       
    

    public static void main(String[] args) {
        
        frmLogin form = new frmLogin();
        form.setVisible(true);
    }
}
